FROM python:3.9
WORKDIR /usr/app
ENV PYTHONUNBUFFERED=1
RUN apt update && \
    apt-get -y install netcat
COPY  requirements.txt .
RUN pip3 install -r requirements.txt
COPY . /usr/app
ENTRYPOINT ["/usr/app/entrypoint.sh"]