import { User } from "@feats/auth/entities";

export const exampleUsers: User[] = [
    {
        id: "1",
        firstName: "John",
        lastName: "Doe",
        email: "john-doe@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=1",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
    {
        id: "1",
        firstName: "Jane",
        lastName: "Doe",
        email: "jane-doe@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=2",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
    {
        id: "1",
        firstName: "Mark",
        lastName: "Kowalski",
        email: "mark-kowalski@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=3",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
    {
        id: "1",
        firstName: "Olivia",
        lastName: "Parker",
        email: "olivia-parker@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=4",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
    {
        id: "1",
        firstName: "James",
        lastName: "Smith",
        email: "james-smith@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=6",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
    {
        id: "1",
        firstName: "Emma",
        lastName: "Johnson",
        email: "emma-johnson@gmail.com",
        profileImage: "https://i.pravatar.cc/150?img=5",
        permissions: [],
        role: "admin",
        createdAt: new Date(),
        lastActiveAt: new Date(),
    },
]