"""add date column

Revision ID: 3827dc34985f
Revises: 00ea8039740e
Create Date: 2022-10-12 20:13:54.826497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3827dc34985f'
down_revision = '00ea8039740e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'created_at')
    # ### end Alembic commands ###
